### PR TITLE
Fix for issue # 61

### PR DESCRIPTION
**Pull request by azatsman**
There are two commits in this pull request:
1. Matrix initialization and comparisons are modified to expose a bug in <code>C_block_form.cl</code>.
2. <code>C_block_form.cl</code> is modified so the modified matrix comparison passes.

### CODE REVIEW

**Comment by tomdeakin** [comment]
Thanks for spotting this. It's always tricky getting the indexes write with this example!

I've managed to fix #61 by solving an issue with the index calculation. This means that the matrix is still written to with nice strides. You noted that the performance was reduced with your proposed fix, and this is probably down to strides writes to C. The fix I've just pushed 6f3e21d956ee726d09ddcc0b1d6fa846fc0546a3 gets the correct answers writing contiguously to C. As such we won't merge in your commit c380e08


The changes to matrix initialisation look good, but we'll need the changes in all the relevant places in the code base. We have C and Python exercises and solutions too. Are you able to replicate your proposed fix in the other Solutions and Exercises in all 3 languages?

**Comment by azatsman** [comment]
Do I understand correctly that you want me to replicate the matrix initialization in C and Python ?  

If I remember correctly, the fix was only in the *.cl part, which you have fixed, and which should be the same for all three languages -- or have I forgotten this more than I thought ? 

    On Wednesday, August 2, 2017 10:23 AM, Tom Deakin <notifications@github.com> wrote:
 

 Thanks for spotting this. It's always tricky getting the indexes write with this example!I've managed to fix #61 by solving an issue with the index calculation. This means that the matrix is still written to with nice strides. You noted that the performance was reduced with your proposed fix, and this is probably down to strides writes to C. The fix I've just pushed 6f3e21d gets the correct answers writing contiguously to C. As such we won't merge in your commit c380e08The changes to matrix initialisation look good, but we'll need the changes in all the relevant places in the code base. We have C and Python exercises and solutions too. Are you able to replicate your proposed fix in the other Solutions and Exercises in all 3 languages?—

**Comment by tomdeakin** [comment]
One of your commits has code which changes initialisation. If you're happy not to merge this in we can leave it, but if you'd like that part merged then it'll need to go everywhere. Your call..

**Comment by azatsman** [comment]
Modified initialization and comparison functions in C, Cpp and Python for more rigorous testing of the results.

**Pull request closed without merging**
